# Generated by Django 5.2.5 on 2025-09-08 13:59

import board.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('q', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('max_jobs', models.PositiveIntegerField(default=1)),
                ('is_featured_package', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=board.models.product_image_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=160)),
                ('company_name', models.CharField(blank=True, default='', max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.URLField(blank=True, default='')),
                ('location', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=board.models.employer_logo_upload_path)),
                ('description', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('credits_total', models.PositiveIntegerField(default=0)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
                ('posting_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='board.postingpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=80)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='board.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=160)),
                ('compensation_type', models.CharField(choices=[('hourly', 'Hourly'), ('yearly', 'Yearly'), ('percent', '% split')], default='hourly', max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_split', models.PositiveIntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('resident', 'Resident'), ('intern', 'Intern'), ('locum', 'Locum')], max_length=20, null=True)),
                ('relocation_assistance', models.BooleanField(default=False)),
                ('posting_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_apply_url', models.URLField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='board.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(blank=True, null=True, upload_to=board.models.application_resume_upload_path)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='board.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('registration_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('new_grad', 'Canadian New Grad'), ('credentialed', 'Completed Credentialing'), ('pce_written', 'Completed Written PCE')], max_length=20)),
                ('opportunity_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('resident', 'Resident'), ('intern', 'Intern'), ('locum', 'Locum')], max_length=20, null=True)),
                ('current_location', models.CharField(max_length=160)),
                ('open_to_relocation', models.BooleanField(default=False)),
                ('relocation_where', models.CharField(blank=True, default='', max_length=200)),
                ('need_sponsorship', models.BooleanField(default=False)),
                ('seeking_immigration', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('position_desired', models.CharField(blank=True, default='', max_length=160)),
                ('is_registered_canada', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to=board.models.resume_upload_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_apply_click', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='board.job')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('credits_total', models.PositiveIntegerField(default=0)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='board.employer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.postingpackage')),
            ],
        ),
    ]
