# Generated by Django 5.2.5 on 2025-09-09 00:27

import board.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('q', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_jobs', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=board.models.product_image_upload_path)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=160)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=board.models.employer_logo_upload_path)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='board.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=160)),
                ('job_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('resident', 'Resident'), ('intern', 'Intern'), ('locum', 'Locum')], max_length=32)),
                ('compensation_type', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('yearly', 'Yearly'), ('percent', '% Split')], max_length=16)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_split', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('posting_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('relocation_assistance', models.BooleanField(default=False)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_apply_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='board.employer')),
            ],
            options={
                'ordering': ['-posting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=board.models.application_resume_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='board.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('position_desired', models.CharField(blank=True, max_length=160)),
                ('current_location', models.CharField(blank=True, max_length=160)),
                ('registration_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('new_grad', 'Canadian New Grad'), ('credentialing', 'Completed Credentialing'), ('pce_written', 'Completed Written PCE')], max_length=32)),
                ('opportunity_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('resident', 'Resident'), ('intern', 'Intern'), ('locum', 'Locum')], max_length=32)),
                ('open_to_relocation', models.BooleanField(default=False)),
                ('relocation_where', models.CharField(blank=True, max_length=200)),
                ('need_sponsorship', models.BooleanField(default=False)),
                ('seeking_immigration', models.BooleanField(default=False)),
                ('resume', models.FileField(blank=True, null=True, upload_to=board.models.resume_upload_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_total', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='board.employer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='board.postingpackage')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
