# Generated by Django 5.2.5 on 2025-09-15 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['company_name', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posting_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='jobalert',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'ordering': ['last_name', 'first_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='postingpackage',
            options={'ordering': ['order', 'name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='purchasedpackage',
            options={'ordering': ['-purchased_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={'ordering': ['-saved_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchased_package',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_type',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='percent_split',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Used when compensation type is 'split' (e.g., 40 for 40%).", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postingpackage',
            name='allows_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postingpackage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('hourly', 'Hourly'), ('split', 'Percent split')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='external_apply_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('casual', 'Casual'), ('temporary', 'Temporary'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='posting_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='q',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='need_sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='open_to_relocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='position_desired',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='registration_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='relocation_where',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='seeking_immigration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='code',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='max_jobs',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='board.job'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='board.jobseeker'),
        ),
    ]
