# Generated by Django 5.2.5 on 2025-09-09 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingpackage',
            name='purchase_valid_days',
            field=models.PositiveIntegerField(default=365, help_text='How long (in days) after purchase the credits remain valid.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
