# Generated by Django 5.2.5 on 2025-09-16 14:51

import board.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingpackage',
            name='package_expires_days',
            field=models.PositiveIntegerField(default=365, help_text='When a package is purchased, credits expire N days later.'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Contact person', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='How long each job post can run.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=board.models.resume_upload_path),
        ),
    ]
