# Generated by Django 5.2.5 on 2026-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
