# Generated by Django 5.2.5 on 2025-09-09 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_postingpackage_purchase_valid_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingpackage',
            name='purchase_valid_days',
            field=models.PositiveIntegerField(default=365, help_text='How many days credits remain usable after purchase.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_total',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
