# Generated by Django 5.2.5 on 2025-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_postingpackage_package_expires_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor'), ('resident', 'Resident'), ('intern', 'Intern'), ('locum', 'Locum')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='percent_split',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
