# Generated by Django 5.2.5 on 2025-09-09 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_postingpackage_purchase_valid_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_total',
            field=models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
