# Generated by Django 5.2.5 on 2025-09-16 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_job_job_type_alter_job_percent_split'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedjob',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='title',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('jobseeker', 'job')},
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(default='Resume', max_length=200),
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='saved_at',
        ),
    ]
