# Generated by Django 5.2.5 on 2025-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_savedjob_options_remove_emailtemplate_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('type', models.CharField(choices=[('fixed', 'Fixed amount (cents)'), ('percent', 'Percent (%)')], default='fixed', max_length=10)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveIntegerField(default=0, help_text='0–100 for percent discounts')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('use_stripe', models.BooleanField(default=False)),
                ('stripe_public_key', models.CharField(blank=True, default='', max_length=200)),
                ('stripe_secret_key', models.CharField(blank=True, default='', max_length=200)),
                ('use_paypal', models.BooleanField(default=False)),
                ('paypal_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=20)),
                ('paypal_client_id', models.CharField(blank=True, default='', max_length=200)),
                ('paypal_client_secret', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
    ]
