# Generated by Django 5.2.5 on 2025-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_discountcode_paymentgatewayconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(blank=True, default='', help_text='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('host_user', models.CharField(blank=True, default='', max_length=255)),
                ('host_password', models.CharField(blank=True, default='', max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email settings',
                'verbose_name_plural': 'Email settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='Physiotherapy Jobs Canada', max_length=200)),
                ('admin_email', models.EmailField(blank=True, default='', max_length=254)),
                ('default_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='percent_split_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='percent_split_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
