# Generated by Django 5.2.5 on 2025-10-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_add_jobseeker_timestamps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='percent_split_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='percent_split_min',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='postingpackage',
            name='updated_at',
        ),
    ]
