# Generated by Django 5.2.5 on 2025-10-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_delete_emailsettings_delete_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PhysiotherapyJobsCanada', max_length=200)),
                ('default_from_email', models.CharField(default='PhysiotherapyJobsCanada <no-reply@yourdomain.com>', help_text='Used as the FROM address in outgoing emails.', max_length=200)),
                ('email_backend', models.CharField(choices=[('console', 'Console (for development)'), ('smtp', 'SMTP (send real emails)')], default='console', help_text='Pick Console while testing, switch to SMTP for production.', max_length=20)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=300)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
