# Generated by Django 5.2.5 on 2025-10-03 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-order_date', '-id']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_status',
            field=models.CharField(blank=True, default='paid', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
