# Generated by Django 5.2.5 on 2025-10-06 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_invoice_options_invoice_gateway_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_packages', to='board.invoice'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='source',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual'), ('', 'Unspecified')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_cents',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('paypal', 'PayPal'), ('', 'Unspecified')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['is_approved'], name='board_emplo_is_appr_52e026_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['company_name'], name='board_emplo_company_8f66c5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['employer', 'order_date'], name='board_invoi_employe_7214f3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order_status'], name='board_invoi_order_s_417dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'posting_date'], name='board_job_is_acti_587747_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['featured', 'posting_date'], name='board_job_feature_766e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobseeker',
            index=models.Index(fields=['user'], name='board_jobse_user_id_0afe1f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedpackage',
            index=models.Index(fields=['employer', 'purchased_at'], name='board_purch_employe_8418d3_idx'),
        ),
    ]
