# Generated by Django 5.2.5 on 2025-10-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_add_remaining_cols'),
    ]

    operations = [
        # ---------------- JobSeeker profile fields ----------------
        migrations.AddField(
            model_name='jobseeker',
            name='is_registered_canada',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(max_length=50, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='current_location',
            field=models.CharField(max_length=150, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='open_to_relocate',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='relocate_where',
            field=models.CharField(max_length=150, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='requires_sponsorship',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='seeking_immigration',
            field=models.CharField(max_length=10, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='position_desired',
            field=models.CharField(max_length=150, blank=True, default=''),
        ),

        # ---------------- PostingPackage ----------------
        migrations.AddField(
            model_name='postingpackage',
            name='credits',
            field=models.PositiveIntegerField(default=1),
            preserve_default=True,
        ),

        # ---------------- Job application routing ----------------
        migrations.AddField(
            model_name='job',
            name='apply_email',
            field=models.EmailField(max_length=254, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
