# Generated by Django 5.2.5 on 2025-10-31 17:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0029_merge_contract_missing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WidgetTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("html", models.TextField(help_text="Embeddable snippet (iframe or script).")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["slug"]},
        ),
        migrations.AlterModelOptions(name="application", options={"ordering": ["-created_at"]}),
        migrations.AlterModelOptions(name="discountcode", options={"ordering": ["code"]}),
        migrations.AlterModelOptions(name="emailtemplate", options={"ordering": ["key"]}),
        migrations.AlterModelOptions(name="employer", options={"ordering": ["company_name"]}),
        migrations.AlterModelOptions(name="invoice", options={"ordering": ["-order_date", "-id"]}),
        migrations.AlterModelOptions(name="job", options={"ordering": ["-posting_date", "-id"]}),
        migrations.AlterModelOptions(name="jobseeker", options={"ordering": ["last_name", "first_name"]}),
        migrations.AlterModelOptions(
            name="paymentgatewayconfig",
            options={"verbose_name": "Payment Gateway Config", "verbose_name_plural": "Payment Gateway Config"},
        ),
        migrations.AlterModelOptions(name="postingpackage", options={"ordering": ["price", "name"]}),
        migrations.AlterModelOptions(name="purchasedpackage", options={"ordering": ["-purchased_at"]}),
        migrations.AlterModelOptions(name="sitesettings", options={"verbose_name_plural": "Site settings"}),

        migrations.RenameField(model_name="emailtemplate", old_name="is_active", new_name="is_enabled"),
        migrations.RenameField(model_name="resume", old_name="created_at", new_name="uploaded_at"),

        migrations.RemoveField(model_name="discountcode", name="amount"),
        migrations.RemoveField(model_name="discountcode", name="applies_to_package"),
        migrations.RemoveField(model_name="discountcode", name="percent_off"),
        migrations.RemoveField(model_name="emailtemplate", name="slug"),
        migrations.RemoveField(model_name="emailtemplate", name="updated_at"),
        migrations.RemoveField(model_name="invoice", name="discount_code"),
        migrations.RemoveField(model_name="invoice", name="external_id"),
        migrations.RemoveField(model_name="invoice", name="gateway"),
        migrations.RemoveField(model_name="paymentgatewayconfig", name="created_at"),
        migrations.RemoveField(model_name="paymentgatewayconfig", name="is_active"),
        migrations.RemoveField(model_name="paymentgatewayconfig", name="name"),
        migrations.RemoveField(model_name="paymentgatewayconfig", name="paypal_client_secret"),
        migrations.RemoveField(model_name="paymentgatewayconfig", name="paypal_mode"),
        migrations.RemoveField(model_name="sitesettings", name="facebook_page"),
        migrations.RemoveField(model_name="sitesettings", name="instagram_account"),
        migrations.RemoveField(model_name="sitesettings", name="reddit_sub"),
        migrations.RemoveField(model_name="sitesettings", name="site_logo"),
        migrations.RemoveField(model_name="sitesettings", name="site_name"),
        migrations.RemoveField(model_name="sitesettings", name="updated_at"),

        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="applications", to="board.resume"
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="applicable_package",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="discounts", to="board.postingpackage"
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="kind",
            field=models.CharField(choices=[("amount", "$ off"), ("percent", "% off")], default="amount", max_length=10),
        ),
        migrations.AddField(model_name="discountcode", name="uses_total", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(
            model_name="discountcode",
            name="value",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=9),
        ),

        migrations.AddField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="mode",
            field=models.CharField(choices=[("test", "Test/Sandbox"), ("live", "Live")], default="test", max_length=10),
        ),
        migrations.AddField(
            model_name="paymentgatewayconfig",
            name="paypal_secret",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(model_name="purchasedpackage", name="duration_days", field=models.PositiveIntegerField(default=30)),
        migrations.AddField(model_name="purchasedpackage", name="expires_at", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="purchasedpackage", name="notes", field=models.TextField(blank=True)),
        migrations.AddField(model_name="resume", name="original_filename", field=models.CharField(blank=True, max_length=255)),

        # 🔧 The broken default was here. Use a real datetime default:
        migrations.AddField(
            model_name="sitesettings",
            name="brand_logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),

        migrations.AlterField(model_name="application", name="cover_letter", field=models.TextField(blank=True)),
        migrations.AlterField(
            model_name="discountcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(model_name="discountcode", name="max_uses_per_user", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AlterField(model_name="discountcode", name="max_uses_total", field=models.PositiveIntegerField(blank=True, null=True)),
        migrations.AlterField(model_name="emailtemplate", name="key", field=models.CharField(max_length=100, unique=True)),
        migrations.AlterField(model_name="emailtemplate", name="subject", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="employer", name="company_description", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="employer", name="company_name", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="employer", name="credits", field=models.IntegerField(default=0)),
        migrations.AlterField(model_name="employer", name="location", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(model_name="employer", name="logo", field=models.ImageField(blank=True, null=True, upload_to="employer_logos/")),
        migrations.AlterField(model_name="employer", name="name", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(model_name="employer", name="phone", field=models.CharField(blank=True, max_length=50)),
        migrations.AlterField(model_name="employer", name="website", field=models.URLField(blank=True)),
        migrations.AlterField(model_name="invoice", name="amount", field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
        migrations.AlterField(model_name="invoice", name="currency", field=models.CharField(default="CAD", max_length=10)),
        migrations.AlterField(
            model_name="invoice",
            name="processor",
            field=models.CharField(choices=[("stripe", "Stripe"), ("paypal", "PayPal"), ("admin", "Admin")], default="admin", max_length=10),
        ),
        migrations.AlterField(model_name="invoice", name="processor_reference", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(choices=[("paid", "Paid"), ("pending", "Pending"), ("failed", "Failed"), ("refunded", "Refunded")], default="paid", max_length=10),
        ),
        migrations.AlterField(model_name="invoice", name="total_cents", field=models.IntegerField(default=0)),
        migrations.AlterField(model_name="job", name="apply_email", field=models.EmailField(blank=True, max_length=254)),
        migrations.AlterField(model_name="job", name="apply_url", field=models.URLField(blank=True)),
        migrations.AlterField(model_name="job", name="apply_via", field=models.CharField(choices=[("Email", "Email"), ("URL", "URL")], max_length=10)),
        migrations.AlterField(model_name="job", name="compensation_max", field=models.IntegerField(blank=True, null=True)),
        migrations.AlterField(model_name="job", name="compensation_min", field=models.IntegerField(blank=True, null=True)),
        migrations.AlterField(model_name="job", name="compensation_type", field=models.CharField(choices=[("Hourly", "Hourly"), ("Yearly", "Yearly"), ("Split", "Split")], max_length=10)),
        migrations.AlterField(model_name="job", name="expiry_date", field=models.DateField(default=django.utils.timezone.now)),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(choices=[("Full-time", "Full-time"), ("Part-time", "Part-time"), ("Contractor", "Contractor"), ("Casual", "Casual"), ("Locum", "Locum"), ("Temporary", "Temporary")], max_length=20),
        ),
        migrations.AlterField(model_name="job", name="location", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="job", name="posting_date", field=models.DateField(default=django.utils.timezone.now)),
        migrations.AlterField(model_name="job", name="split_percent", field=models.IntegerField(blank=True, null=True)),
        migrations.AlterField(model_name="job", name="title", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="jobseeker", name="current_location", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="jobseeker", name="first_name", field=models.CharField(max_length=120)),
        migrations.AlterField(
            model_name="jobseeker",
            name="is_registered_canada",
            field=models.CharField(choices=[("Yes", "Yes"), ("No", "No")], max_length=3),
        ),
        migrations.AlterField(model_name="jobseeker", name="last_name", field=models.CharField(max_length=120)),
        migrations.AlterField(
            model_name="jobseeker",
            name="open_to_relocate",
            field=models.CharField(choices=[("Yes", "Yes"), ("No", "No")], max_length=3),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="opportunity_type",
            field=models.CharField(choices=[("Full-time", "Full-time"), ("Part-time", "Part-time"), ("Contractor", "Contractor"), ("Temporary", "Temporary"), ("Locum", "Locum"), ("Casual", "Casual")], max_length=20),
        ),
        migrations.AlterField(model_name="jobseeker", name="position_desired", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="jobseeker", name="relocate_where", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(
            model_name="jobseeker",
            name="requires_sponsorship",
            field=models.CharField(choices=[("Yes", "Yes"), ("No", "No")], max_length=3),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="seeking_immigration",
            field=models.CharField(choices=[("Yes", "Yes"), ("No", "No")], max_length=3),
        ),
        migrations.AlterField(model_name="paymentgatewayconfig", name="paypal_client_id", field=models.CharField(blank=True, max_length=200)),
        migrations.AlterField(model_name="paymentgatewayconfig", name="stripe_public_key", field=models.CharField(blank=True, max_length=200)),
        migrations.AlterField(model_name="paymentgatewayconfig", name="stripe_secret_key", field=models.CharField(blank=True, max_length=200)),
        migrations.AlterField(model_name="postingpackage", name="name", field=models.CharField(max_length=255)),
        migrations.AlterField(model_name="postingpackage", name="price", field=models.DecimalField(decimal_places=2, max_digits=9)),
        migrations.AlterField(model_name="purchasedpackage", name="credits_granted", field=models.PositiveIntegerField(default=0)),
        migrations.AlterField(model_name="purchasedpackage", name="credits_remaining", field=models.PositiveIntegerField(default=0)),
        migrations.AlterField(model_name="purchasedpackage", name="external_reference", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(
            model_name="purchasedpackage",
            name="source",
            field=models.CharField(choices=[("admin", "admin"), ("stripe", "stripe"), ("paypal", "paypal")], default="admin", max_length=10),
        ),
        migrations.AlterField(model_name="resume", name="file", field=models.FileField(upload_to="resumes/")),
        migrations.AlterField(model_name="sitesettings", name="bottom_banner_html", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="sitesettings", name="google_analytics_id", field=models.CharField(blank=True, max_length=50)),
        migrations.AlterField(model_name="sitesettings", name="mapbox_token", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(model_name="sitesettings", name="seo_meta_description", field=models.TextField(blank=True)),
        migrations.AlterField(model_name="sitesettings", name="seo_meta_title", field=models.CharField(blank=True, max_length=255)),
        migrations.AlterField(model_name="sitesettings", name="side_banner_html", field=models.TextField(blank=True)),
    ]
