# Generated by Django 5.2.5 on 2025-11-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_postingpackage_feature_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_facebook', models.BooleanField(default=False)),
                ('use_reddit', models.BooleanField(default=False)),
                ('use_instagram', models.BooleanField(default=False)),
                ('facebook_page_id', models.CharField(blank=True, help_text='Facebook Page ID to post new jobs to.', max_length=100)),
                ('facebook_access_token', models.CharField(blank=True, help_text='Long-lived Facebook Page access token.', max_length=255)),
                ('facebook_message_template', models.CharField(blank=True, help_text='Optional message template. Use {{ title }}, {{ location }}, {{ url }}.', max_length=255)),
                ('reddit_client_id', models.CharField(blank=True, max_length=200)),
                ('reddit_client_secret', models.CharField(blank=True, max_length=200)),
                ('reddit_username', models.CharField(blank=True, max_length=200)),
                ('reddit_password', models.CharField(blank=True, help_text='Script password or app-specific password.', max_length=200)),
                ('reddit_subreddit', models.CharField(blank=True, help_text='Subreddit name, e.g. physiotherapyjobs', max_length=100)),
                ('reddit_title_template', models.CharField(blank=True, help_text='Optional Reddit post title template. Use {{ title }}, {{ location }}.', max_length=255)),
                ('reddit_body_template', models.TextField(blank=True, help_text='Optional Reddit body template. Use {{ title }}, {{ location }}, {{ url }}.')),
                ('instagram_business_account_id', models.CharField(blank=True, help_text='Instagram Business Account ID connected to your Facebook Page.', max_length=200)),
                ('instagram_access_token', models.CharField(blank=True, help_text='Access token with permission to post on Instagram.', max_length=255)),
                ('instagram_caption_template', models.CharField(blank=True, help_text='Optional caption template. Use {{ title }}, {{ location }}, {{ url }}.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Posting Config',
                'verbose_name_plural': 'Social Posting Config',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
