# Generated by Django 5.2.5 on 2025-11-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_socialpostingconfig_alter_job_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_webhook_url',
            field=models.URLField(blank=True, help_text='Optional webhook URL for auto-posting jobs when they go live. Typically a Make.com/Zapier/n8n webhook URL.'),
        ),
    ]
