# Generated by Django 5.2.5 on 2025-11-26 00:02

import board.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_sitesettings_social_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='Make.com / Zapier / n8n webhook URL to receive job payloads.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Config',
            },
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchasedpackage',
            options={'ordering': ['-purchased_at', '-id']},
        ),
        migrations.RenameField(
            model_name='paymentgatewayconfig',
            old_name='stripe_public_key',
            new_name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='max_uses_per_user',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='max_uses_total',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='uses_total',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mapbox_token',
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary login email.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('employer', 'Employer'), ('admin', 'Admin'), ('upload', 'Upload')], default='employer', max_length=10),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='applicable_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='board.postingpackage'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='kind',
            field=models.CharField(choices=[('amount', '$ off'), ('percent', '% off')], max_length=10),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='employer',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.employer_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_registered_canada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='open_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='position_desired',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='requires_sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='seeking_immigration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='mode',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.branding_upload_path),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='facebook_access_token',
            field=models.CharField(blank=True, help_text='Page access token with permissions to post.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='facebook_message_template',
            field=models.CharField(blank=True, help_text='Optional Facebook post text template. Use {{ title }}, {{ location }}.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='instagram_access_token',
            field=models.CharField(blank=True, help_text='Access token used for Instagram publishing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID for posting.', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='instagram_caption_template',
            field=models.CharField(blank=True, help_text='Optional caption template. Use {{ title }}, {{ location }}.', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_body_template',
            field=models.TextField(blank=True, help_text='Optional Reddit text body template.'),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_client_id',
            field=models.CharField(blank=True, help_text='Reddit app client ID.', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_client_secret',
            field=models.CharField(blank=True, help_text='Reddit app client secret.', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_username',
            field=models.CharField(blank=True, help_text='Bot account username.', max_length=100),
        ),
    ]
