# Generated by Django 5.2.5 on 2025-11-26 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_webhookconfig_delete_emailtemplate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookConfig',
        ),
        migrations.DeleteModel(
            name='WidgetTemplate',
        ),
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-is_featured', '-posting_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewayconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchasedpackage',
            options={'ordering': ['-purchased_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='socialpostingconfig',
            options={'verbose_name': 'Social posting config', 'verbose_name_plural': 'Social posting config'},
        ),
        migrations.RenameField(
            model_name='discountcode',
            old_name='valid_to',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='discountcode',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_cents',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.RemoveField(
            model_name='job',
            name='split_percent',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='facebook_message_template',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='instagram_business_account_id',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='instagram_caption_template',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='reddit_body_template',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='compensation_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='is_published_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employer_cta_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employer_cta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_hero_title_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='job_alert_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='job_alert_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mapbox_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_reddit_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='instagram_business_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.resume'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='kind',
            field=models.CharField(choices=[('percent', 'Percent off'), ('amount', 'Fixed amount off')], default='percent', max_length=20),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='employer',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_logos/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processor',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_via',
            field=models.CharField(choices=[('email', 'Email'), ('url', 'URL')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Salary', 'Salary'), ('Split', 'Split'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='relocation_assistance',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not available', 'Not available')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_registered_canada',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='open_to_relocate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contractor', 'Contractor'), ('Temporary', 'Temporary'), ('Locum', 'Locum'), ('Casual', 'Casual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='position_desired',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='requires_sponsorship',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='seeking_immigration',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='mode',
            field=models.CharField(choices=[('test', 'Test/Sandbox'), ('live', 'Live')], default='test', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='facebook_access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_client_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_client_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_subreddit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_title_template',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
