# Generated by Django 5.2.5 on 2025-11-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0036_emailtemplate_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
