# Generated by Django 5.2.5 on 2025-11-28 14:57

import board.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0038_full_restore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('html', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewayconfig',
            options={'verbose_name': 'Payment Gateway Config', 'verbose_name_plural': 'Payment Gateway Config'},
        ),
        migrations.RenameField(
            model_name='discountcode',
            old_name='valid_from',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='socialpostingconfig',
            old_name='facebook_enabled',
            new_name='use_facebook',
        ),
        migrations.RenameField(
            model_name='socialpostingconfig',
            old_name='instagram_enabled',
            new_name='use_instagram',
        ),
        migrations.RenameField(
            model_name='socialpostingconfig',
            old_name='reddit_enabled',
            new_name='use_reddit',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='valid_to',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='sponsorship_required',
        ),
        migrations.RemoveField(
            model_name='postingpackage',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='postingpackage',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='postingpackage',
            name='product_expires_days',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='webhookconfig',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='webhookconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='discountcode',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(default='legacy', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='requires_sponsorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='mode',
            field=models.CharField(choices=[('test', 'Test/Sandbox'), ('live', 'Live')], default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='paypal_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='postingpackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postingpackage',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reddit_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='facebook_page_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='job_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='reddit_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='reddit_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='reddit_refresh_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='reddit_subreddit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='kind',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=board.models.employer_logo_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.employer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processor_reference',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchased_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.purchasedpackage'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_cents',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_via',
            field=models.CharField(choices=[('email', 'Email'), ('url', 'URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('salary', 'Salary'), ('range', 'Range'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='is_registered_canada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='open_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='position_desired',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='relocate_where',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='seeking_immigration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='processor',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('admin', 'Admin')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='use_stripe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='credits',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_granted',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_remaining',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.employer'),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='source',
            field=models.CharField(default='stripe', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.jobseeker'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Physiotherapy Jobs Canada', max_length=255),
        ),
    ]
