# Generated by Django 5.2.5 on 2025-11-28 16:20

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_widgettemplate_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bottom_banner_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branding_favicon',
            field=models.ImageField(blank=True, upload_to=board.models.branding_upload_path),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branding_footer_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branding_logo',
            field=models.ImageField(blank=True, upload_to=board.models.branding_upload_path),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branding_primary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='branding_secondary_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mapbox_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='side_banner_html',
            field=models.TextField(blank=True),
        ),
    ]
