# Generated by Django 5.2.5 on 2025-11-30 17:33

import board.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0043_sitesettings_nullable_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlertSignup',
            fields=[
            ],
            options={
                'verbose_name': 'Job Alert Signup',
                'verbose_name_plural': 'Job Alert Signups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.jobalert',),
        ),
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentgatewayconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='applicable_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.postingpackage'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.employer_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processor_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchased_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.purchasedpackage'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('salary', 'Salary'), ('range', 'Range'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='current_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='position_desired',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='relocate_where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='mode',
            field=models.CharField(default='live', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='paypal_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='paypal_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='paypal_webhook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='processor',
            field=models.CharField(default='stripe', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='credits',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='postingpackage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_granted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_remaining',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='expires_at',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='branding_favicon',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.branding_upload_path),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='branding_logo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.branding_upload_path),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='facebook_page_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='job_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialpostingconfig',
            name='reddit_subreddit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='widgettemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
