# Generated by Django 5.2.5 on 2025-12-01 23:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0044_jobalertsignup_alter_application_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAlertSignup',
        ),
        migrations.RenameField(
            model_name='paymentgatewayconfig',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='paymentgatewayconfig',
            old_name='stripe_public_key',
            new_name='stripe_publishable_key',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='socialpostingconfig',
            old_name='use_facebook',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='key',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchased_package',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_cents',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='paypal_client_secret',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='paypal_webhook_id',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='stripe_webhook_secret',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='use_paypal',
        ),
        migrations.RemoveField(
            model_name='paymentgatewayconfig',
            name='use_stripe',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='facebook_page_token',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='instagram_access_token',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='job_template',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='reddit_client_id',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='reddit_client_secret',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='reddit_refresh_token',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='use_instagram',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='use_reddit',
        ),
        migrations.RemoveField(
            model_name='webhookconfig',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='currency',
            field=models.CharField(default='CAD', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='gateway_name',
            field=models.CharField(default='Stripe', max_length=50),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialpostingconfig',
            name='instagram_business_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='kind',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='processor',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='compensation_type',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Hourly', 'Hourly'), ('Per-visit', 'Per-visit'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobalert',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='opportunity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_granted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='credits_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_hero_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='PT Jobs', max_length=255),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widgettemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
