# Generated by Django 5.2.5 on 2025-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0045_delete_jobalertsignup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlertSignup',
            fields=[
            ],
            options={
                'verbose_name': 'Job Alert Signup',
                'verbose_name_plural': 'Job Alert Signups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.jobalert',),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
