# Generated by Django 5.2.5 on 2025-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0046_jobalertsignup_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(default='legacy_template', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
