# Generated by Django 5.2.5 on 2025-12-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0047_emailtemplate_body_emailtemplate_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAlertSignup',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='bottom_banner_html',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='branding_footer_html',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='branding_primary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='branding_secondary_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='employer_column_content',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='employer_column_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='google_analytics_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='jobseeker_column_content',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='jobseeker_column_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='mapbox_token',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='reddit_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='seo_meta_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='side_banner_html',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_webhook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='facebook_page_id',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='instagram_business_id',
        ),
        migrations.RemoveField(
            model_name='socialpostingconfig',
            name='reddit_subreddit',
        ),
        migrations.RemoveField(
            model_name='webhookconfig',
            name='secret',
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('import', 'Import'), ('employer', 'Employer')], db_index=True, default='employer', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
