"""
Django settings for pt_jobs project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

# ------------------------------------------------------------
# Hosts / CSRF
# ------------------------------------------------------------
# Allow local + Railway + your domain by default, without needing extra env vars.
_raw_hosts = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts if h.strip()]

# Always allow Railway domains (covers web-production-xxxx.up.railway.app etc.)
# Django allows leading-dot patterns for subdomains.
for h in [".railway.app", ".up.railway.app"]:
    if h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)

# Always allow your site domains (safe even if not live yet)
for h in ["physiotherapyjobscanada.ca", "www.physiotherapyjobscanada.ca", "media.physiotherapyjobscanada.ca"]:
    if h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)

# CSRF trusted origins (needed once you use HTTPS + forms on custom domain)
CSRF_TRUSTED_ORIGINS = []
for origin in [
    "https://*.railway.app",
    "https://*.up.railway.app",
    "https://physiotherapyjobscanada.ca",
    "https://*.physiotherapyjobscanada.ca",
]:
    CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Required for django-import-export admin templates
    "import_export",

    "board",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pt_jobs.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # Django defaults (keep these)
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
                "django.template.context_processors.media",
                "django.template.context_processors.tz",
            ],
        },
    },
]

WSGI_APPLICATION = "pt_jobs.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Toronto"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media (local default)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -------------------------------------------------------------------
# STORAGE: Default local, optional Cloudflare R2 for MEDIA via STORAGES
# -------------------------------------------------------------------
R2_ACCOUNT_ID = os.environ.get("R2_ACCOUNT_ID", "").strip()
R2_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID", "").strip()
R2_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY", "").strip()
R2_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "").strip()
R2_PUBLIC_BASE_URL = os.environ.get("R2_PUBLIC_BASE_URL", "").strip()

# Default STORAGES (works even without django-storages installed)
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
}

# Switch MEDIA storage to R2 only when all required vars are present
if R2_ACCOUNT_ID and R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY and R2_BUCKET_NAME:
    # Requires: pip install django-storages boto3
    if "storages" not in INSTALLED_APPS:
        INSTALLED_APPS.append("storages")

    STORAGES["default"] = {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"}

    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME

    AWS_S3_REGION_NAME = "auto"
    AWS_S3_ENDPOINT_URL = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    AWS_S3_ADDRESSING_STYLE = "path"

    # Public bucket access (no signed querystrings)
    AWS_QUERYSTRING_AUTH = False

    # MEDIA_URL must be PUBLIC (custom domain OR r2.dev), not the S3 API endpoint
    if R2_PUBLIC_BASE_URL:
        MEDIA_URL = R2_PUBLIC_BASE_URL.rstrip("/") + "/"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email settings (SendGrid via Railway env vars)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.sendgrid.net")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "apikey")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

# Site "from" email
SITE_FROM_EMAIL = os.environ.get("SITE_FROM_EMAIL", "no-reply@physiotherapyjobscanada.ca")
DEFAULT_FROM_EMAIL = SITE_FROM_EMAIL

# Admin notifications
ADMIN_EMAILS = os.environ.get("ADMIN_EMAILS", "").strip()
SITE_ADMIN_EMAIL = (ADMIN_EMAILS.split(",")[0].strip() if ADMIN_EMAILS else os.environ.get("SITE_ADMIN_EMAIL", "").strip())
